name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Package
      run: mvn package

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-java@v3
        with:
          java-version: '11'
          distruibution: 'adopt'
          package: '*jar'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
